# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0459aada797ccbad620363c57a9b263ad6c05dfbf35a4b2a1e82ed948d9de1c34f05eb0efe0f17fbdc89bd38321ae6de2c13ddb8d8041d6bacc7e4b9ddcbebe4

test:
  secret_key_base: b064c51da006c9d61dae545cc0ecbc9ffd2941feecf777ea0986f3d9538ad2bab6852ed6cf4a04ea1e3e44fb03f860a50f3b77eb1d5255f471f4e92cbdee0510

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
